# Generated by Django 3.2.21 on 2023-12-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temoignageApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temoignesmodel',
            old_name='username',
            new_name='agresseur',
        ),
    ]
