# Generated by Django 5.0.1 on 2024-01-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignageApp', '0002_rename_username_temoignesmodel_agresseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignesmodel',
            name='agresseur',
            field=models.CharField(max_length=50, verbose_name='Agresseur'),
        ),
    ]
