# Generated by Django 4.2.7 on 2024-01-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temoignageApp", "0003_alter_temoignesmodel_agresseur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temoignesmodel",
            name="agresseur",
            field=models.CharField(max_length=250, verbose_name="Agresseur"),
        ),
    ]
