# Generated by Django 4.2.7 on 2024-01-24 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("temoignageApp", "0005_alter_temoignesmodel_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temoignesmodel",
            name="temoin",
        ),
        migrations.AddField(
            model_name="temoignesmodel",
            name="message",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=600,
                verbose_name="Message",
            ),
            preserve_default=False,
        ),
    ]
